- hosts: localhost
  connection: local
  tasks:
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      state: present
      name: testvm-with-dv
      namespace: vmexamples
      labels:
        app: test
      instancetype:
        name: u1.medium
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
            name: testdv
          spec:
            sourceRef:
              kind: DataSource
              name: fedora
              namespace: openshift-virtualization-os-images
      spec:
        domain:
          devices: {}
        volumes:
          - dataVolume:
              name: testdv
            name: datavolume
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                # The default username is: fedora
                ssh_authorized_keys:
                  - ssh-ed25519 AAAA...
            name: cloudinit
      wait: true