- name: Listen for changes to the CMDB
  hosts: all

  sources:
    - name: cmdb_webhook
      ansible.eda.webhook:
        port: 5000

  rules:
    - name: Snapshot VM
      condition: event.payload.type == "snapshot"
      action:
        run_job_template:
          name: vm-take-snapshot
          organization: Default

    - name: Reconcile CI with CMDB
      condition: event.payload.type == "cmdb-changed"
      action:
        run_job_template:
         name: reconcile-configuration-item
