- name: Listen for Machine resource events
  hosts: localhost

  sources:
  - sabre1041.eda.k8s:
      api_version: kubevirt.io/v1
      kind: VirtualMachine
      namespace: vmexamples

  rules:
    - name: Run Job on VM start
      condition:
#        all:
#        - event.type == 'MODIFIED'
        event.resource.spec.running == true
      action:
        run_job_template:
          name: modify_motd
          organization: Default
        debug:
