- hosts: localhost
  connection: local
  tasks:
  - name: Create virtual machine
    kubevirt.core.kubevirt_vm:
      state: present
      name: testvm
      namespace: vmexamples
      instancetype:
        name: u1.medium
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
            name: testdv
          spec:
            sourceRef:
              kind: DataSource
              name: fedora
              namespace: openshift-virtualization-os-images
            storage:
              resources: {}
      spec:
        template:
          spec:
            accessCredentials:
              - sshPublicKey:
                  propagationMethod:
                    noCloud: {}
                  source:
                    secret:
                      secretName: 'authorized-keys'
            readinessProbe:
              initialDelaySeconds: 120
              periodSeconds: 20
              tcpSocket:
                port: 22
              timeoutSeconds: 10
        domain:
          devices:
            interfaces:
              - masquerade: {}
                name: default
        volumes:
          - dataVolume:
              name: testdv
            name: datavolume
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: fedora
                password: redhat123!
                chpasswd: { expire: False }
            name: cloudinit
