---
- hosts: "{{ vm_name }}"
  become: true
  tasks:
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Write motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '644'
