---
apiVersion: v1
kind: Namespace
metadata:
  name: vmexamples
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-access
  namespace: vmexamples
  type: Opaque
stringData:
  token: <generated-token>
  host:  <controller URL>
