---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
      annotations:
      name: vmexamples-service-account
      namespace: vmexamples
---
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: role-vmexamples-service-account
    namespace: vmexamples
  rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: role-vmexamples-service-account-binding
    namespace: vmexamples
  subjects:
  - kind: ServiceAccount
    name: vmexamples-service-account
  roleRef:
    kind: Role
    name: role-vmexamples-service-account
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ansible
  namespace: vmexamples
  annotations:
    kubernetes.io/service-account.name: "vmexamples-service-account"
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: ocp-credential
  namespace: vmexamples
spec:
  name: ocp-credential
  organization: Default
  connection_secret: controller-access
  description: "OpenShift platform cre"
  type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://kubernetes.default.svc.cluster.local
  kubernetes_bearer_token_secret: ansible
  runner_pull_policy: IfNotPresent
