---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: createvm
  namespace: vmexamples
spec:
  connection_secret: controller-access
  name: Create VM
  project: OCPvirt-Automation
  playbook: ansible/create-vm.yml
  inventory: Demo Inventory
  credentials: ocp-credential
---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: deletevm
  namespace: vmexamples
spec:
  connection_secret: controller-access
  name: Delete VM
  project: OCPvirt-Automation
  playbook: ansible/delete-vm.yml
  inventory: Demo Inventory
  credentials: ocp-credential
---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: modify_motd
  namespace: vmexamples
spec:
  connection_secret: controller-access
  name: modify-motd
  project: OCPvirt-Automation
  playbook: ansible/update_motd.yml
  inventory: Demo Inventory
  credentials: ocp-credential
